### ISSUE TITLE
(Not A Bug) BCNM/KSNM Drop/Loot tracker [WIP]

### ISSUE THREAD

**Issue by RavenTactics** [Demiurge-DSP/feedback-and-info#33]
**Feedback or issue :**  BCNM/KSNM Drop/Loot tracker
All items and loot tiers verified against ffxiclopedia.fandom.com for current retail era. I.E. I didn't look at any history/past versions of the pages. 

**Key:** 
> Name - Zone - # cap 
> If it's working as per (https://github.com/DarkstarProject/darkstar/issues/2782) it'll have a check
> This is a Work In Progress and I will continue to edit and update. 

### Level 20 Cloudy Orb (3man - 20 Beastmen's Seals)

- [x] Charming Trio - Balga's Dais - 3man
	**All:**
	Mannequin Hands (100%)
	
	**One:**
	Toad Oil (???%)
	Potion (???%)
	Potion +1 (???%)
	Air Spirit Pact (???%)
	Cotton Cloth (???%)
	
	**One:**
	Mythril Beastcoin (???%)
	Ganko (???%)
	Wool Cloth (???%)
	Platoon Disc (???%)
	Grass Cloth (???%)
	Linen Cloth (???%)
	
	**Zero to One:**
	Platoon Cutter (???%)
	
	**Zero to Two:**
	Fiend Blood (???%)

	**Unknown groupings:**
	Platoon Edge (???%)
	Platoon Gun (???%)
	Platoon Spatha (???%)
	Platoon Pole (???%)
	Gunromaru (???%)
	Mannequin Head (???%)
	Scroll of Drain (???%)
	Beastman Blood (???%)

- [ ] Crustacean Conundrum - Waughroon Shrine
	**One of:**
	Beetle Quiver (???%)
	Fish Oil Broth (???%)

	**All of:**
	Land Crab Meat (100%)
	Mannequin Body (100%

	**Unknown groupings:**
	Platoon Axe (???%)
	Platoon Bow (???%)
	Platoon Cesti (???%)
	Platoon Dagger (???%)
	Platoon Lance (???%)
	Platoon Sword (???%)
	Platoon Mace (???%)
	Platoon Zaghnal (???%)
	Brass Ingot (???%)
	Bronze Sheet (???%)
	Bronze Ingot (???%)
	Crab Shell (???%)
	Mannequin Hands (???%)
	Mannequin Head (???%)
	Mythril Beastcoin (???%)

- [ ] Shooting Fish - Horlais Peak

	**All of:**
	Mannequin Head (100%)
	Shall Shell (100%)

	**One of:**
	Mythril Beastcoin (37%)
	Black Rock (7%)
	Purple Rock (3%)
	White Rock (10%)
	Platoon Bow (10%)
	Platoon Disc (15%)
	Platoon Gun (15%)
	Platoon Mace (10%)

	**One of:**
	Mythril Beastcoin (37%)
	Green Rock (5%)
	Yellow Rock (4%)
	Blue Rock (4%)
	Red Rock (4%)
	Translucent Rock (11%)
	Platoon Cesti (13%)
	Platoon Cutter (10%)
	Platoon Spatha (8%)
	Platoon Zaghnal (10%)

	**Zero to One of:**
	Pugil Scales (19%)
	Shall Shell (14%)

	**Zero to One of:**
	Mannequin Body (7%)

- [x] Wings of Fury - Ghelsba Outpost

	**All of:**
	Bat Fang(100%)

	**One of:**
	Thunder Spirit Pact(30.6%)
	Scroll of Invisible(31.9%)
	Scroll of Sneak (12.5%)
	Scroll of Deodorize(22.2%)

	**One of:**
	Ganko (15.3%)
	Platoon Edge (13.9%)
	Platoon Axe (8.3%)
	Platoon Pole (9.7%)
	Platoon Dagger (12.5%)
	Mythril Beastcoin(44.4%)
	Translucent Rock (5.6%)

	**One of:**
	Gunromaru (11.1%)
	Platoon Dagger(13.9%)
	Platoon Edge (13.9%)
	Platoon Lance (4.2%)
	Platoon Sword (18.1%)
	Purple Rock (9.7%)
	Red Rock (6.9%)
	White Rock (1.4%)
	Black Rock (2.8%)
	Green Rock (2.8%)
	Yellow Rock (1.4%)
	Blue Rock (6.9%)

	**Zero to One of:**
	Astral Ring (16.7%)
	Bat Wing (44.4%)

### Level 30 Sky Orb (3man - 30 Beastmen's Seals)

- [ ] Birds of a Feather - Waughroon Shrine 
- [ ] Carapace Combatants - Horlais Peak
- [ ] Creeping Doom - Balga's Dais
- [ ] Die by the Sword - Qu'Bia Arena
- [ ] Petrifying Pair - Ghelsba Outpost
- [ ] Dropping Like Flies - Horlais Peak
- [ ] Grove Guardians - Waughroon Shrine
- [ ] Harem Scarem - Balga's Dais
- [ ] Let Sleeping Dogs Die - Qu'Bia Arena
- [ ] Toadal Recall - Ghelsba Outpost
  
### Level 40 Star Orb (3man - 40 Beastmen's Seals)

- [ ] Under Observation - Horlais Peak-Trade not accepted
- [ ] Undying Promise - Qu'Bia Arena-Trade not accepted
- [ ] Royal Jelly - Waughroon Shrine-Trade not accepted
- [ ] Royal Succession - Balga's Dais-Trade not accepted
- [ ] Factory Rejects - Qu'Bia Arena-Trade not accepted
- [ ] Steamed Sprouts - Balga's Dais-Trade not accepted
- [ ] Tails of Woe - Horlais Peak-Trade not accepted
- [ ] The Worm's Turn - Waughroon Shrine-Trade not accepted
  
### Level 50 Comet Orb (3man & 6man - 50 Beastmen's Seals)

- [ ] The Final Bout - Waughroon Shrine-Trade not accepted
- [ ] An Awful Autopsy - Qu'Bia Arena-Trade not accepted
- [ ] Eye of the Tiger - Horlais Peak-No option given
- [ ] Rapid Raptors - Balga's Dais-Trade not accepted
- [x] Hostile Herbivores - Horlais Peak- Works
- [ ] 3, 2, 1... - Waughroon Shrine-Trade not accepted
- [ ] Idol Thoughts - Qu'Bia Arena-Trade not accepted
- [ ] Treasure and Tribulations - Balga's Dais-Trade not accepted
  
### Level 60 Moon Orb (3man & 6man - 60 Beastmen's Seals)

- [ ] Celery - Qu'Bia Arena-Trade not accepted
- [ ] Shots in the Dark - Horlais Peak-Trade not accepted
- [x] Up in Arms - Waughroon Shrine-Works
- [ ] Wild Wild Whiskers - Balga's Dais-Trade not accepted
- [ ] Amphibian Assault - Sacrificial Chamber-No option given
- [ ] Brothers D'Aurphe - Qu'Bia Arena-Trade not accepted
- [ ] Demolition Squad - Qu'Bia Arena-Trade not accepted
- [ ] Dismemberment Brigade- Horlais Peak-Trade not accepted
- [ ] Divine Punishers - Balga's Dais-Trade not accepted
- [ ] Grimshell Shocktroopers - Waughroon Shrine-No option given
- [x] Jungle Boogymen - Sacrificial Chamber-Works
- [ ] Kindred Spirits - Throne Room-Trade not accepted
- [ ] Legion XI Comitatensis - Chamber of Oracles-Trade not accepted
  
### Atropos Orb (6man - 30 Kindred's Seals)

- [x] Contaminated Colosseum - Horlais Peak-Works
- [ ] Infernal Swarm - Qu'Bia Arena-Trade not accepted
- [ ] Moa Constrictors - Balga's Dais-Trade not accepted
- [x] Prehistoric Pigeons - Waughroon Shrine- Works
- [ ] The Scarlet King - Chamber of Oracles-Trade not accepted
  
### Clotho Orb (6man - 30 Kindred's Seals)

- [ ] Cactuar Suave - Chamber of Oracles-Trade not accepted
- [ ] Come Into My Parlor - Qu'Bia Arena-Trade not accepted
- [ ] Copycat - Waughroon Shrine-Trade not accepted
- [x] Double Dragonian - Horlais Peak-Works
- [ ] Seasons Greetings - Balga's Dais- Trade not accepted

### Lachesis Orb (6man - 30 Kindred's Seals)

- [ ] E-vase-ive Action - Qu'Bia Arena-Trade not accepted
- [ ] Eye of the Storm - Chamber of Oracles-Trade not accepted
- [x] Operation Desert Swarm - Waughroon Shrine-Works
- [ ] Royale Ramble - Balga's Dais-Trade not accepted
- [ ] Today's Horoscope - Horlais Peak-Trade not accepted
  
### Themis Orb (18man - 99 Kindred's Seals)

- [x] Early Bird Catches the Wyrm - Balga's Dais-Works
- [x] Horns of War - Horlais Peak-Works
- [x] The Hills Are Alive - Waughroon Shrine

REPLACE THIS TEXT

- [x] **I understand that I should fill in with an x or check these boxes for yes/no**  

- [x] **I understand that using the AT `@` symbol tells github to notify a user of that name**  

- [x] **I understand that I** **_should not_** **use this form to report missing features or general bugs with Darkstar**  

- [x] **I understand that if this is reporting a bug specific to this server I need to be very detailed, including info such as but not limited to my position and the date and time of occurrence, any NPC or items involved, etc. etc.**  
#
